yaml:
  level:
    str: 字符串不需要加双引号
    num: 666
    Dnum: 555.00
    birth: 2020/11/25 16:22:22
    list: [one,two,three]
    users:
      - name: zhangsan
        salary: 1288.0
      - name: lisi
        salary: 2588.0
ac